### ISSUE TITLE
The extension is not installable in Visual Studio Code Community if not in root C:\

### ISSUE THREAD

**Issue by AmauryVanEspen** [sql-bi/BravoTemplateEditor#2]
Hello,
The extension is not installable in Visual Studio Code Community if not in root C:\
as my installation of VS is community and in D:\
it does not install at all

find the log below
`28/12/2022 15:25:04 - Microsoft VSIX Installer
28/12/2022 15:25:04 - -------------------------------------------
28/12/2022 15:25:04 - vsixinstaller.exe version:
28/12/2022 15:25:04 - 17.4.2119
28/12/2022 15:25:04 - -------------------------------------------
28/12/2022 15:25:04 - Command line parameters:
28/12/2022 15:25:04 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\m0m0\Downloads\SQLBI.bravo-template-editor-1.0.1.vsix
28/12/2022 15:25:04 - -------------------------------------------
28/12/2022 15:25:04 - Microsoft VSIX Installer
28/12/2022 15:25:04 - -------------------------------------------
28/12/2022 15:25:04 - Initializing Install...
28/12/2022 15:25:04 - Détails de l'extension...
28/12/2022 15:25:04 - 	Identifier         : bravo-template-editor
28/12/2022 15:25:04 - 	Name               : Bravo Template Editor
28/12/2022 15:25:04 - 	Author             : SQLBI
28/12/2022 15:25:04 - 	Version            : 1.0.1
28/12/2022 15:25:04 - 	Description        : Bravo Template Editor is the companion editor of Bravo for Power BI. It allows to edit, compile and preview custom date templates for Power BI reports.
28/12/2022 15:25:04 - 	Locale             : en-US
28/12/2022 15:25:04 - 	MoreInfoURL        : 
28/12/2022 15:25:04 - 	InstalledByMSI     : False
28/12/2022 15:25:04 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
28/12/2022 15:25:04 - 
28/12/2022 15:25:04 - 	SignatureState     : Unsigned
28/12/2022 15:25:04 - 	Produits pris en charge : 
28/12/2022 15:25:04 - 		Microsoft.VisualStudio.Code
28/12/2022 15:25:04 - 			Version : 
28/12/2022 15:25:04 - 			ProductArchitecture : x86
28/12/2022 15:25:04 - 
28/12/2022 15:25:04 - 	Références         : 
28/12/2022 15:25:04 - Détails de la signature...
28/12/2022 15:25:04 - 	Extension is not signed.
28/12/2022 15:25:04 - 
28/12/2022 15:25:04 - Recherche des produits applicables...
28/12/2022 15:25:04 - Produit installé trouvé - Emplacement global
28/12/2022 15:25:04 - Produit installé trouvé - Visual Studio Community 2022
28/12/2022 15:25:04 - VSIXInstaller.NoApplicableSKUsException: Une ou plusieurs extensions sont destinées à Visual Studio Code. Essayez de les installer dans Visual Studio Code.
   à VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   à VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   à VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   à VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   à VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   à VSIXInstaller.App.Initialize()
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
`

**Comment by albertospelta** [comment]
Hi @AmauryVanEspen !
Bravo's template editor is an extension of _Visual Studio Code_ (VSCode), a free, lightweight code editor provided by Microsoft. 
VSCode is a different tool from the _Visual Studio IDE_, which is a more complex and full featured development environment.

From the log message it appears that the installation failed because _Visual Studio Code_ is not installed on the computer. 
The extension installer found the _Visual Studio Community 2022_ product installed but not VSCode.

```
Produit installé trouvé - Visual Studio Community 2022 

VSIXInstaller.NoApplicableSKUsException: Une ou plusieurs extensions sont destinées à Visual Studio Code. 
Essayez de les installer dans Visual Studio Code
```
You can download VSCode from here https://code.visualstudio.com/ and - once it's installed - you should be able to install the extension.

Please let me know if this solves the issue.
Thanks!
